export const checkpoints: Checkpoint[] = [
  {
    name: "KCFO",
    altitudeFt: { value: 5500, unit: "FT" },
    temp: { value: 3, unit: "C" },
    windDir: { value: 41, unit: "DEG" },
    windVel: { value: 5, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
  {
    name: "TOC 6500",
    altitudeFt: { value: 6500, unit: "FT" },
    temp: { value: 6, unit: "C" },
    windDir: { value: 285, unit: "DEG" },
    windVel: { value: 5, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
  {
    name: "Bennet",
    altitudeFt: { value: 6500, unit: "FT" },
    temp: { value: -2, unit: "C" },
    windDir: { value: 20, unit: "DEG" },
    windVel: { value: 6, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
  {
    name: "TOC 7500",
    altitudeFt: { value: 7500, unit: "FT" },
    temp: { value: -2, unit: "C" },
    windDir: { value: 20, unit: "DEG" },
    windVel: { value: 6, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
  {
    name: "Dry Creek",
    altitudeFt: { value: 7500, unit: "FT" },
    temp: { value: -2, unit: "C" },
    windDir: { value: 20, unit: "DEG" },
    windVel: { value: 6, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
  {
    name: "Radio Tower",
    altitudeFt: { value: 7500, unit: "FT" },
    temp: { value: -2, unit: "C" },
    windDir: { value: 20, unit: "DEG" },
    windVel: { value: 6, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
  {
    name: "Well/Lake",
    altitudeFt: { value: 7500, unit: "FT" },
    temp: { value: -2, unit: "C" },
    windDir: { value: 20, unit: "DEG" },
    windVel: { value: 6, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
  {
    name: "Gary",
    altitudeFt: { value: 7500, unit: "FT" },
    temp: { value: -2, unit: "C" },
    windDir: { value: 20, unit: "DEG" },
    windVel: { value: 6, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
  // {
  //   name: "DESC 5700",
  //   altitudeFt: { value: 7500, unit: "FT" },
  //   temp: { value: 0, unit: "C" },
  //   windDir: { value: 0, unit: "DEG" },
  //   windVel: { value: 0, unit: "KTS" },
  //   magneticVariance: { value: -7, unit: "DEG" },
  // },
  {
    name: "KAKO",
    altitudeFt: { value: 4700, unit: "FT" },
    temp: { value: 0, unit: "C" },
    windDir: { value: 0, unit: "DEG" },
    windVel: { value: 0, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
];

export const legs: LegParams[] = [
  [0, 1, "climb", 5500, 0, 89, -7, true],
  [1, 2, "cruise", 6500, 5.1, 89, -7, false],
  [2, 3, "climb", 6500, 0, 89, -7, false],
  [3, 4, "cruise", 7500, 10, 89, -7, false],
  [4, 5, "cruise", 7500, 13.5, 61, -7, false],
  [5, 6, "cruise", 7500, 10, 61, -7, false],
  [6, 7, "cruise", 7500, 10, 61, -7, false],
  [7, 8, "cruise", 7500, 17.5, 61, -7, false],
  [8, 9, "cruise", 7500, 17.5, 61, -7, false],
];
