const checkpoints: Checkpoint[] = [
  {
    name: "KCFO",
    altitudeFt: { value: 5500, unit: "FT" },
    temp: { value: 25, unit: "C" },
    windDir: { value: 0, unit: "DEG" },
    windVel: { value: 0, unit: "KTS" },
    magneticVariance: { value: 7, unit: "DEG" },
  },
  {
    name: "TOC 6500",
    altitudeFt: { value: 6500, unit: "FT" },
    temp: { value: 15, unit: "C" },
    windDir: { value: 0, unit: "DEG" },
    windVel: { value: 0, unit: "KTS" },
    magneticVariance: { value: 7, unit: "DEG" },
  },
  {
    name: "Bennet",
    altitudeFt: { value: 6500, unit: "FT" },
    temp: { value: 15, unit: "C" },
    windDir: { value: 0, unit: "DEG" },
    windVel: { value: 0, unit: "KTS" },
    magneticVariance: { value: 7, unit: "DEG" },
  },
  {
    name: "TOC 7500",
    altitudeFt: { value: 7500, unit: "FT" },
    temp: { value: 15, unit: "C" },
    windDir: { value: 0, unit: "DEG" },
    windVel: { value: 0, unit: "KTS" },
    magneticVariance: { value: 7, unit: "DEG" },
  },
  {
    name: "Dry Creek",
    altitudeFt: { value: 7500, unit: "FT" },
    temp: { value: 15, unit: "C" },
    windDir: { value: 0, unit: "DEG" },
    windVel: { value: 0, unit: "KTS" },
    magneticVariance: { value: 7, unit: "DEG" },
  },
  {
    name: "Radio Tower",
    altitudeFt: { value: 7500, unit: "FT" },
    temp: { value: 15, unit: "C" },
    windDir: { value: 0, unit: "DEG" },
    windVel: { value: 0, unit: "KTS" },
    magneticVariance: { value: 7, unit: "DEG" },
  },
  {
    name: "Well/Lake",
    altitudeFt: { value: 7500, unit: "FT" },
    temp: { value: 15, unit: "C" },
    windDir: { value: 0, unit: "DEG" },
    windVel: { value: 0, unit: "KTS" },
    magneticVariance: { value: 7, unit: "DEG" },
  },
  {
    name: "Gary",
    altitudeFt: { value: 7500, unit: "FT" },
    temp: { value: 15, unit: "C" },
    windDir: { value: 0, unit: "DEG" },
    windVel: { value: 0, unit: "KTS" },
    magneticVariance: { value: 7, unit: "DEG" },
  },
  // {
  //   name: "DESC 5700",
  //   altitudeFt: { value: 7500, unit: "FT" },
  //   temp: { value: 15, unit: "C" },
  //   windDir: { value: 0, unit: "DEG" },
  //   windVel: { value: 0, unit: "KTS" },
  //   magneticVariance: { value: 7, unit: "DEG" },
  // },
  {
    name: "KAKO",
    altitudeFt: { value: 4700, unit: "FT" },
    temp: { value: 15, unit: "C" },
    windDir: { value: 0, unit: "DEG" },
    windVel: { value: 0, unit: "KTS" },
    magneticVariance: { value: 7, unit: "DEG" },
  },
];

export const legs: LegV2[] = [
  toLegV2(checkpoints[0], checkpoints[1], "climb", 5500, 0, 89, 7, true),
  toLegV2(checkpoints[1], checkpoints[2], "cruise", 6500, 5.1, 89, 7),
  toLegV2(checkpoints[2], checkpoints[3], "climb", 6500, 0, 89, 7),
  toLegV2(checkpoints[3], checkpoints[4], "cruise", 7500, 10, 89, 7),
  toLegV2(checkpoints[4], checkpoints[5], "cruise", 7500, 13.5, 61, 7),
  toLegV2(checkpoints[5], checkpoints[6], "cruise", 7500, 10, 61, 7),
  toLegV2(checkpoints[6], checkpoints[7], "cruise", 7500, 10, 61, 7),
  toLegV2(checkpoints[7], checkpoints[8], "cruise", 7500, 17.5, 61, 7),
  // toLegV2(checkpoints[8], checkpoints[9], "cruise", 7500, 17.5, 61, 7),
];

function toLegV2(
  from: Checkpoint,
  to: Checkpoint,
  type: "climb" | "cruise" | "descend",
  altitudeFt: number,
  distance: number,
  trueCourse: number,
  magneticeVariance: number,
  isStart = false
): LegV2 {
  return {
    name: `${from.name} to ${to.name}`,
    type,
    altitudeFt: { value: altitudeFt, unit: "FT" },
    distance: { value: distance, unit: "NM" },
    from,
    to,
    trueCourse: { value: trueCourse, unit: "DEG" },
    magneticVariance: { value: magneticeVariance, unit: "DEG" },
    isStart,
  };
}
