export const checkpoints: Checkpoint[] = [
  {
    name: "KLIC",
    altitudeFt: { value: 5374, unit: "FT" },
    temp: { value: 3, unit: "C" },
    windDir: { value: 187, unit: "DEG" },
    windVel: { value: 15, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
  {
    name: "TOC 8500 windmills",
    altitudeFt: { value: 8500, unit: "FT" },
    temp: { value: -2, unit: "C" },
    windDir: { value: 200, unit: "DEG" },
    windVel: { value: 15, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
  {
    name: "Agate",
    altitudeFt: { value: 8500, unit: "FT" },
    temp: { value: -2, unit: "C" },
    windDir: { value: 200, unit: "DEG" },
    windVel: { value: 15, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
  {
    name: "Middle Bijou",
    altitudeFt: { value: 8500, unit: "FT" },
    temp: { value: -2, unit: "C" },
    windDir: { value: 200, unit: "DEG" },
    windVel: { value: 15, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
  {
    name: "Bijou",
    altitudeFt: { value: 7500, unit: "FT" },
    temp: { value: -2, unit: "C" },
    windDir: { value: 200, unit: "DEG" },
    windVel: { value: 15, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
  {
    name: "TOD 7500",
    altitudeFt: { value: 7500, unit: "FT" },
    temp: { value: -2, unit: "C" },
    windDir: { value: 200, unit: "DEG" },
    windVel: { value: 15, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
  {
    name: "Bennet",
    altitudeFt: { value: 6500, unit: "FT" },
    temp: { value: -2, unit: "C" },
    windDir: { value: 200, unit: "DEG" },
    windVel: { value: 15, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
  {
    name: "KCFO",
    altitudeFt: { value: 5515, unit: "FT" },
    temp: { value: -2, unit: "C" },
    windDir: { value: 200, unit: "DEG" },
    windVel: { value: 15, unit: "KTS" },
    magneticVariance: { value: -7, unit: "DEG" },
  },
];

export const legs: LegParams[] = [
  [0, 1, "climb", 5374, 0, 307, -7, true],
  [1, 2, "cruise", 8500, 17, 307, -7, false],
  [2, 3, "cruise", 8500, 8.2, 307, -7, false],
  [3, 4, "cruise", 8500, 9, 307, -7, false],
  [4, 5, "cruise", 8500, 9, 307, -7, false],
  [5, 6, "cruise", 7500, 2, 307, -7, false],
  [6, 7, "cruise", 6500, 5, 307, -7, false],
  [7, -1, "cruise", 6500, 0, 307, -7, false],
];
